"use strict";

const $ = (id) => document.getElementById(id);

async function load() {
  const cfg = await chrome.storage.local.get([
    "baseUrl",
    "apiToken",
    "projectId",
    "defaultWho",
  ]);
  $("baseUrl").value = cfg.baseUrl || "";
  $("apiToken").value = cfg.apiToken || "";
  $("projectId").value = cfg.projectId || "";
  $("defaultWho").value = cfg.defaultWho || "";
}

function setStatus(msg, cls) {
  const el = $("status");
  el.textContent = msg;
  el.className = cls || "";
}

// Parse a kenboard "Copy onboard link" URL and fill base_url / project_id /
// api_token. The link is generated by category.html → copyOnboardLink as
// `<origin>/onboard/cat/<catId>/project/<projectId>?token=<key>`.
function applyOnboardLink(raw) {
  const value = raw.trim();
  if (!value) return;
  let url;
  try {
    url = new URL(value);
  } catch {
    setStatus("Not a valid URL.", "error");
    return;
  }
  const m = url.pathname.match(/\/onboard\/cat\/[^/]+\/project\/([^/]+)\/?$/);
  if (!m) {
    setStatus("Doesn't look like an onboard link (…/onboard/cat/…/project/…).", "error");
    return;
  }
  const token = url.searchParams.get("token");
  $("baseUrl").value = url.origin;
  $("projectId").value = decodeURIComponent(m[1]);
  if (token) $("apiToken").value = token;
  setStatus(
    token
      ? "Filled from onboard link — review and Save."
      : "Filled base URL and project — link had no token, add it manually.",
    token ? "success" : "error",
  );
}

async function save(e) {
  e.preventDefault();
  await chrome.storage.local.set({
    baseUrl: $("baseUrl").value.trim().replace(/\/$/, ""),
    apiToken: $("apiToken").value.trim(),
    projectId: $("projectId").value.trim(),
    defaultWho: $("defaultWho").value.trim(),
  });
  setStatus("Saved.", "success");
}

async function test() {
  const baseUrl = $("baseUrl").value.trim().replace(/\/$/, "");
  const token = $("apiToken").value.trim();
  const projectId = $("projectId").value.trim();
  if (!baseUrl || !token || !projectId) {
    setStatus("Fill base URL, API token and project ID first.", "error");
    return;
  }
  setStatus("Testing…");
  try {
    // Probe the project-scoped task list, NOT GET /api/v1/projects:
    // a per-project / onboarding token can't be scope-checked against the
    // cross-project /projects endpoint (the server can't resolve a single
    // project_id for it) and is rejected with 403. /tasks?project=<id>
    // resolves the project, so this validates base URL + token + the
    // token's scope on the exact project tasks will land in.
    const resp = await fetch(
      `${baseUrl}/api/v1/tasks?project=${encodeURIComponent(projectId)}`,
      {
        // See comment in popup.js — Firefox auto-attaches the kenboard
        // session cookie cross-origin which throws the auth middleware
        // onto the cookie-CSRF path. Omit credentials → pure bearer.
        credentials: "omit",
        headers: { Authorization: `Bearer ${token}` },
      },
    );
    if (!resp.ok) {
      setStatus(`HTTP ${resp.status}`, "error");
      return;
    }
    const tasks = await resp.json();
    setStatus(`OK — project reachable (${tasks.length} task(s)).`, "success");
  } catch (err) {
    setStatus(`Error: ${err.message}`, "error");
  }
}

document.addEventListener("DOMContentLoaded", () => {
  load();
  $("ext-version").textContent = `v${chrome.runtime.getManifest().version}`;
  $("settings").addEventListener("submit", save);
  $("test").addEventListener("click", test);
  $("onboardLink").addEventListener("input", (e) => applyOnboardLink(e.target.value));
});
